name: OWASP ZAP
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan OWASP Juice Shop
    permissions: write-all
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://demo.owasp-juice.shop/'
