name: OWASP ZAP
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan 4th-IR website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://www.4th-ir.com/'
