name: OWASP ZAP
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan MLK Kilimanjaro Dev
    permissions: write-all
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://urology-dev.kilimanjaro-production.app/'
